name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/apps/TestPortfolio
          git pull origin main
          cd client
          npm install
          npm run build
          cp -r build/* /var/www/html  # Adjust this as needed

          cd ../server
          npm install
          npm run build
          pm2 restart all
        EOF
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
