name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to the app directory
          cd ~/apps/TestPortfolio

          # Pull the latest code
          git pull origin main

          # Navigate to and build the client
          cd client
          npm install
          npm run build

          # Move the build output to the correct location
          # For example, if the build output should go to /var/www/html, do:
          # cp -r build/* /var/www/html

          # Navigate to and set up the server
          cd ../server
          npm install
          npm run build
          pm2 restart all
        EOF
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
